# Generated by Django 3.1.7 on 2021-04-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saveToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=100, null=True)),
                ('oauth_token_secret', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
