# Generated by Django 3.1.7 on 2021-04-01 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('id_socmed', models.CharField(max_length=100)),
                ('account_type', models.IntegerField(choices=[(0, 'Facebook'), (1, 'Twitter')], default=0)),
                ('active', models.BooleanField(default=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token_exp', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('oauth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_token_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('user_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='frontend.account')),
            ],
        ),
    ]
